apiVersion: apps/v1
kind: Deployment

metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story-app
  template:
    metadata:
      labels:
        app: story-app
    spec:
      containers:
        - name: story-app
          image: sdhiren/story-app-kube:latest
          env:
            - name: STORY_FOLDER
              # value: story
              valueFrom:
                configMapKeyRef:
                  name: env-data
                  key: foldername
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
      volumes: 
        - name: story-volume
          persistentVolumeClaim:
            claimName: mypvc