apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  volumeName: mypv
  resources:
    requests:
      storage: 1Gi
  # volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
