apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-app
  template:
    metadata:
      labels:
        app: kube-app
    spec:
      containers:
        - name: kube-application
          image: sdhiren/kube-image:3